### ISSUE TITLE
Support load template that's already within DOM

### ISSUE THREAD

**Issue by Nness** [aurelia/loader#1]
This include html page bundled with templates, server side MVC provide initial templates on page request.

1. Html page bundled with templates or library template bundled with child templates. This can provide third party plugin with a nicer way to package and bundle all components together and minify them. Decrease load or import process.

2. Server side MVC provide initial templates. This can allow fast initial load for large applications. Or small application that only have 1 or 2 modules.

**Comment by EisenbergEffect** [comment]
Absolutely! Thanks for creating this issue. One of the things we are working on right now is bundling HTML Imports via Polymer's vulcanizer tool. We expect to update our loader to account for how that delivers templates and as part of that we'll have a solution for this issue as well. We'll update this issue with details around that as we establish them. Work is being done on that now by @ahmedshuhel

**Comment by rafanami** [comment]
Is this to address Isomorphic Javascript capabilities?

**Comment by EisenbergEffect** [comment]
@rafanami Not necessarily. Isomorphic involves a bunch of other stuff. This has more to do with deployment and packaging scenarios.

**Comment by rafanami** [comment]
Thanks Rob for the clarification. And keep it up on this awesome work!

**Comment by EisenbergEffect** [comment]
FYI. We haven't forgotten about this. We've recently made some new improvements to the template loading system going out in the next release. We're also making good progress on bundling. Once we've got our bundling work done, it will be really easy for us to add this feature.

**Comment by Nness** [comment]
Cool

**Comment by ahmedshuhel** [comment]
@Nness bundling support for `html templates` and `js modules` is coming very soon.

**Comment by capaj** [comment]
@ahmedshuhel very soon? Are there any issues, that prevent you from releasing? Is it possible to see how is the progress? Is it on some branch?

Also excuse my naive question, but wouldn't it be possible to bundle whole aurelia app just by
 1. utilising jspm bundle method(including all js files except those used in polymer web components) to create app's bundle
 2. vulcanizing all html files
 3. concatenating results of 1. and 2. 

?

**Comment by EisenbergEffect** [comment]
We now have support in master to load templates from a view bundle. The cli also has the capability to create these bundles. This should go out in the next set of releases. We will work on putting together a blog post to explain how to use it all.

**Comment by csaloio1** [comment]
Very much looking forward to learning more about loading templates from view bundles.
