### ISSUE TITLE
Bundled hierarchical templates fall back to html source dir

### ISSUE THREAD

**Issue by CharlesPockert** [aurelia/loader#10]
I have a plugin which has the following structure:

```
grid
-- grid.js
-- grid.html
pager
-- pager.js
-- pager.html
```

I can't seem to get this bundling using the CLI, so I've created the bundles manually (after debugging and looking at what paths Aurelia is requesting)

The grid imports the pager

I notice that when the grid is resolved/loaded the `grid.html` is correctly loaded from the bundled templates, but `pager.html` is always loaded from the jspm_packages directory (which is a problem!)

I managed to track it down to `findBundledTemplate` - the first time a template is requested, if the bundle doesn't exist the template is loaded and a promise is queued. It looks like the second request to load comes in before the promise is resolved, so the check for `if(this.bundle)` is skipped (as it's still undefined)

```
      Loader.prototype.findBundledTemplate = function findBundledTemplate(name, entry) {
        var _this2 = this;
        if (this.bundle) {
          var found = this.bundle.getElementById(name);
          if (found) {
            entry.setTemplate(found);
            return Promise.resolve(true);
          }
        } else if (!this.bundleChecked) {
          this.bundleChecked = true;
          var bundleLink = document.querySelector('link[aurelia-view-bundle]');
          if (bundleLink) {
            return this.importBundle(bundleLink).then(function(doc) {
              _this2.bundle = doc;
              var found = _this2.bundle.getElementById(name);
              if (found) {
                entry.setTemplate(found);
                return Promise.resolve(true);
              }
            });
          }
        }
        return Promise.resolve(false);
      };
```

I assume this means that both requests are happening simultaneously or there's something that's not waiting on the original promise

**Comment by CharlesPockert** [comment]
Ah, inspecting the metadata it looks like there's a dependencies property on the incoming template - so maybe because I've not used the CLI the dependencies aren't specified on the template... will see if I can get this working

**Comment by CharlesPockert** [comment]
Ah didn't think "why am I getting a request for the pager template before it's even required?". I was globalizing both resources - the pager so it could be used elsewhere and the grid which is dependent on the pager. 

I suppose this is an edge case really, what are the chances of someone globalizing a resource in a plugin that another part of that plugin/another module is dependent on, and the page happening to request the part at the same time as the application is starting up?

**Comment by orokanasaru** [comment]
It's an edge case, but I just hit it as well. I'm using Razor for my views, so I'm getting 404's because the file doesn't really exist.

**Comment by EisenbergEffect** [comment]
I believe this has been fixed already.
