### ISSUE TITLE
Loading multiple globalized resources from bundle file

### ISSUE THREAD

**Issue by olanod** [aurelia/loader#12]
It seems `findBundledTemplate` is called synchronously for each resource passed to `aurelia.globalizeResources` but the flag set inside `findBundledTemplate`(`this.bundle`) to check if the bundle exists is resolved asynchronously later, loading only the first resource from the bundle.

**Comment by EisenbergEffect** [comment]
@olanod What's the best way to reproduce this? Can you provide a bit more info. I'm not entirely following.

**Comment by EisenbergEffect** [comment]
Wait. I see it.

**Comment by EisenbergEffect** [comment]
Ok, I think I've got it fixed. Give me a couple of minutes and I'll get the patch release out.

**Comment by olanod** [comment]
Nice!
