### ISSUE TITLE
app.html fails to load in chrome after a refresh

### ISSUE THREAD

**Issue by gabor-farkas** [aurelia/loader#13]
- I create an empty directory and open a command prompt. I'm using the brand-new windows 10, with a fresh install of nodejs.
- I run "yo aurelia" and then "gulp watch"
- I open localhost:9000 with chrome 46.0.2467.2 dev-m. (Things work well with iexplore and edge)
- I press F5, and the loading spinner remains there, and the console shows an error: Unhandled promise rejection Error: Error loading "app.html!view" at http://localhost:9000/dist/app.html(…)

What I debugged:
- the importDocument method in aurelia-loader creates the link with the proper URL
- according to the network tab, the document is properly loaded
- in the callback of importElement, the imported document is just an empty html

I've created screenshots:
![aurelia-chrome-anomaly](https://cloud.githubusercontent.com/assets/2929085/9048332/b0459ade-3a38-11e5-8aaa-1898c96a20aa.png)
![aurelia-chrome-anomaly-2](https://cloud.githubusercontent.com/assets/2929085/9048331/b045556a-3a38-11e5-8edd-25f2033d3620.png)

Restarting 'gulp watch' makes things work again for one another time, but things go wrong either on an F5, or when browsersync reloads the page.

Well, this is probably of course not a bug in aurelia, maybe it's just in dev-m, but maybe it's something good to know about.

**Comment by EisenbergEffect** [comment]
Closing as not an issue.
