### ISSUE TITLE
FireFox: Site is not being loaded when webinspector is opened

### ISSUE THREAD

**Issue by lares83** [aurelia/loader#19]
Hi, 
When I launch your skeleton application everything loads fine on firefox, but when I open web inspector and refresh a page, application is not loading. In console I get this error:

Unhandled promise rejection "TypeError: Unexpected anonymous AMD define.
	Evaluating http://localhost:9000/jspm_packages/github/aurelia/loader@0.10.0.js
	Error loading http://localhost:9000/jspm_packages/github/aurelia/loader@0.10.0.js as "aurelia-loader" from http://localhost:9000/jspm_packages/github/aurelia/loader-default@0.11.2/aurelia-loader-default.js"

Firefox Version: 41.0.1

**Comment by EisenbergEffect** [comment]
It is a bug in system.js that was recently discovered and it being worked on.

**Comment by jdanyow** [comment]
https://github.com/systemjs/systemjs/issues/814

**Comment by lares83** [comment]
Thanks for information

**Comment by peterjonathan** [comment]
Hi,
I've been getting a similar problem when changing a js file or refreshing the Aurelia Navigation Skeleton when using firebug and firefox 41.0.1:
system.js (line 5, col 11742): TypeError: Unexpected anonymous AMD define. 	
shim.min.js (line 1444): Unhandled promise rejection
TypeError: Unexpected anonymous AMD define.
	Evaluating http://localhost:9000/jspm_packages/github/aurelia/loader@0.10.0.js
	Error loading http://localhost:9000/jspm_packages/github/aurelia/loader@0.10.0.js as "aurelia-loader" from http://localhost:9000/jspm_packages/github/aurelia/loader-default@0.11.0/aurelia-loader-default.js

Eventually I restarted firefox and used the inspector instead of firebug and the problem went away !

**Comment by EisenbergEffect** [comment]
This is a bug in system.js. There's a fix for it already. I'm not sure if it's released yet or not. Try updating system.js with `jspm dl-loader` and see if that fixes the issue for you.

**Comment by peterjonathan** [comment]
Thankyou for the the speedy response, and suggested fix.
I'm please to say that the "jspm dl-loader" command fixed the issue. 
Am looking forward to gaining some insights into the Aurelia magic.
The ES6 classes and associated templates are beautifully simple - keep up the brilliant work Master Magican !

**Comment by thebravedave** [comment]
I'm using your "Typescript Kit" from
http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started
and I'm getting the same error.

**Comment by Thalvik** [comment]
Same issue here, using FF 42 and FB 2.0.13. The issue was resolved with `jspm dl-loader` for a while, but returned.

**Comment by EisenbergEffect** [comment]
Please report this to system.js.
