### ISSUE TITLE
Use path-resolution of `System` or `require` in System and AMD environments

### ISSUE THREAD

**Issue by Alxandr** [aurelia/loader#2]
Currently, if I use the paths configured in `config.js` for `System.js` to load my viewmodels, it fails to find the html templates, because it's not using the same path resolution. This forces me to spell out the full path of all my view models, so instead of using `routes/index` I have to use `lib/app/routes/index`.

**Comment by EisenbergEffect** [comment]
I'm thinking...if we just use System.normalize first, and then pass that result to our import loading code, that should work, right?

**Comment by Alxandr** [comment]
Yeah. As far as I know that's all you need. Just remember the result from `normalize` can (and should probably) be a promise. Not to mention it doesn't take a string, but a context object (last I checked). However, requirejs users should have the same problem, and they don't have `System.normalize`...

**Comment by EisenbergEffect** [comment]
What about something like this:

```javascript
loadTemplate(url){
    if(url.endsWith('.html')){
      url = url.substring(0, url.length - 5);
    }

    return System.normalize(url).then(newId => {
      if(this.baseViewUrl && !url.startsWith(this.baseViewUrl) && url.indexOf('@') === -1){
        url = join(this.baseViewUrl, url);
      }

      return this.importTemplate(newId + ".html");
    });
  }
```

**Comment by Alxandr** [comment]
Not sure what this `baseViewUrl` is, but otherwise looks great :)

But I'm really unsure about having something like `baseViewUrl` that could mangle stuff up with regards to how other stuff are resolved...

**Comment by EisenbergEffect** [comment]
I'm not quite sure either...but I've got a scenario with my current client where it won't work with just normalize. I'm not sure if its system.js but or not, but it doesn't pick up our * path config. So, baseViewUrl gets set for System.baseUrl or a custom property System.baseViewUrl. And the @ check is to try to detect versioned imported modules and then only join the paths if it isn't already rooted there.

I don't know...this is a pain. The real reason it's as ugly as it is relates to the ES6 module loader missing a hook I really need to tag all imports with some metadata that would solve this ultimately.

Think about it and see if you have any further thoughts.

**Comment by RonnyPfannschmidt** [comment]
well, imho the case is clear aurealia and jspm use path mapping for the app by default, so templates should be mapped exactly the same way

**Comment by EisenbergEffect** [comment]
Any thoughts on the code sample above?

**Comment by RonnyPfannschmidt** [comment]
not sure, but bascially thats not code i wana see in my app - all i want to get is the same mapping for html and js

maybe its enough to extend config.js, after all it explicitly maps js files - the templates however are html

**Comment by EisenbergEffect** [comment]
No, no. That doesn't go in your app. That goes in our template loader abstraction.

**Comment by RonnyPfannschmidt** [comment]
bascially all i want is all bits of the system using the same mapping without me having to set up different kinds of different mappings
right now i have to serve my static files from 2 locations because js is mapped to app for the name mybox and html isnt, and any change i inflict on config.js will be undone by jspm

**Comment by RonnyPfannschmidt** [comment]
i just looked at https://github.com/systemjs/systemjs#plugins - to me it seems clear that systemjs mapping should be used for the templates as well in order to use the same facilities

**Comment by EisenbergEffect** [comment]
We are working on a few options here. One trick is that we would like a solution that works for require-style apis as well. It may be reasonable to support a "degraded" experience for older loaders. Need to think about it.

**Comment by RonnyPfannschmidt** [comment]
i suspect that unless those have resource apis it will be rather problematic

**Comment by EisenbergEffect** [comment]
This should now be fixed on master. It's going out in the next release. Essentially, our view loading now goes through System.js and Require.js first in order to correctly map paths. Also, our plugin api has changed in order for us to be able to get the proper module id info.
