### ISSUE TITLE
Unable to get property 'querySelectorAll' of undefined or null reference when using webcomponents

### ISSUE THREAD

**Issue by obsean** [aurelia/loader#23]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
4.2.4

* **NPM Version:**
3.10.9

* **Browser:**
IE 11

* **Language:**
all

**Current behavior:**

If you add a reference to webcomponents-lite.js then an error "Unable to get property 'querySelectorAll' of undefined or null reference" occurs in aurelia-loader.js at line 38:

requires = value.content.querySelectorAll('require');

This only seems to happen in IE11. I've reproduced it on clean installs using both Aurelia CLI and the JSPM skeleton

**Comment by EisenbergEffect** [comment]
Do you know of a fix for this?

**Comment by obsean** [comment]
The issue above contains a pull request with a fix. I've tested this and it fixes the issue

**Comment by dpinart** [comment]
I'm facing same issue. If using polymer with webcomponents-lite polyfil ie doesn't load anything and it appears 'Unable to get property 'querySelectorAll' of undefined or null reference' error in console. The fix in the obsean's pull request seems to fix this issue.

Is there any chance that this fix is going to be accepted?

**Comment by mikhailshilkov** [comment]
Same issue here. Any chance to get that fix integrated?

**Comment by jamesond** [comment]
Any moves on this?

**Comment by Alexander-Taran** [comment]
fix merged, can be closed
