### ISSUE TITLE
IE 11 Object doesn't support property or method 'load'

### ISSUE THREAD

**Issue by Kukks** [aurelia/loader#24]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
all

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.8

Aurelia-CLI 
0.24.0

* **Browser:**
Internet Explorer 11 

* **Language:**
Typescript

**Current behavior:**
I navigate to my Aurelia website and get multiple errors in the console stating that `Object doesn't support property or method 'load'`. The website loads fine in FF, Chrome, and Edge

Full log is: http://pastebin.com/HCSrufFV

**Expected/desired behavior:**
Website to load without error in IE 11

* **What is the expected behavior?**
Website to load without error in IE 11

* **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
Did you add the polyfills that are required?

**Comment by Kukks** [comment]
Yes, I've installed the `webcomponentsjs` & `raf` polyfills and used the following CLI configuration(there are no docs on polyfill setup for CLI projects):

```
          {
            "name": "performance-now",
            "path": "../node_modules/performance-now/lib",
            "main": "performance-now"
          },
          {
            "name": "raf",
            "path": "../node_modules/raf",
            "main": "index"
          },
          {
            "name": "WeakMap",
            "path": "../node_modules/webcomponents.js/src",
            "main": "WeakMap/WeakMap"
          },
          {
            "name": "MutationObserver",
            "path": "../node_modules/webcomponents.js/src",
            "main": "MutationObserver/MutationObserver"
          },
```

along with 

```
import * as raf from 'raf';
  raf.polyfill();
```
 in my main and I still receive the same errors. Chrome, Firefox, Edge all work fine. Doesn't IE11 already support the MutationObserver in any case?

**Comment by stoffeastrom** [comment]
Can you try and figure out where the error happens? Break on uncaugh exceptions and see where the offending line is? Where is the `.load(`?

**Comment by Kukks** [comment]
Seems to be in `callPlugin`  from requirejs. First one it fails on is "aurelia-templating-resources/compose.html". 
```
                    //Use parentName here since the plugin's name is not reliable,
                    //could be some weird string with no path that actually wants to
                    //reference the parentName's path.
                    plugin.load(map.name, localRequire, load, config);
```
