### ISSUE TITLE
Default lookup folders for custom elements

### ISSUE THREAD

**Issue by andreister** [aurelia/loader#6]
Sensible defaults will allow to get rid of `<require>` tags most of the time - eg. the "getting started" `app.html` would look like this (notice there's no `require`):

```html
<template>
  <nav-bar router.bind="router"></nav-bar>

  <div class="page-host">
    <router-view></router-view>
  </div>
</template>
```

Reason is, custom elements are mostly used in two scenarios:
* better code organization - custom element is used only by the parent template
* remove code duplication - custom element is used by multiple templates

The framework can address both cases without forcing people to write `<require>` tags:
* first lookup in the local template folder
* if nothing found, lookup in some predefined `shared/` folder, or list of configurable shared folders
* if nothing found, yield an error

Apart from allowing to write less code, this approach - hopefully! - forces users to better think about source tree organization, and it's been used in ASPNET MVC for ages so there's nothing new and magical. 

Thoughts?

**Comment by EisenbergEffect** [comment]
How do you account for web components?

**Comment by Aaike** [comment]
i do like the idea of being able to register components beforehand.
for example , in my plugin package i would be able to register the elements with aurealia, maybe something like `.registerElement('date-picker','./date-picker')`
people can then just simple start using the custom element without having to worry where it has to be imported from.

i do understand that this might not be an easy implementation and can cause overheads , but it's worth considering.

**Comment by EisenbergEffect** [comment]
You can do this already using aurelia.globalizeResources

On Tue, Mar 31, 2015 at 12:50 PM, Aaike Van Roekeghem <
notifications@github.com> wrote:

> i do like the idea of being able to register components beforehand.
> for example , in my plugin package i would be able to register the
> elements with aurealia, maybe something like
> .registerElement('date-picker','./date-picker')
> people can then just simple start using the custom element without having
> to worry where it has to be imported from.
>
> i do understand that this might not be an easy implementation and can
> cause overheads , but it's worth considering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aurelia/loader/issues/6#issuecomment-88168978>.
>



-- 
Rob Eisenberg,
President - Blue Spire
www.durandaljs.com

**Comment by shaunluttin** [comment]
`aurelia.globalizeResources` is not exposed in the type definition.

**Comment by EisenbergEffect** [comment]
That api changed a while back. Use `globalResources()`.

**Comment by shaunluttin** [comment]
With `aurelia-framework ^1.0.2` there is no `aureila.globalResources()`.

**Comment by EisenbergEffect** [comment]
`aurelia.use.globalResources()`

**Comment by shaunluttin** [comment]
"TypeError: Cannot read property 'globalResources' of undefined."

**Comment by shaunluttin** [comment]
```
function configure(aurelia: Aurelia, callback: Function) {
    aurelia.use.globalResources('./foo-bar');
}
```

**Comment by shaunluttin** [comment]
Fix:
```
function configure(aurelia: Aurelia, config: FrameworkConfiguration, callback: Function) {
    config.globalResources('./foo-bar');
}
```

**Comment by EisenbergEffect** [comment]
Yes, it depends on whether or not you have the Aurelia object of the FrameworkConfiguration object. The configure method of the app's main.js gets the Aurelia object while the configure method of a plugin gets the FrameworkConfiguration object.

**Comment by shaunluttin** [comment]
I'm building a plugin.
