### ISSUE TITLE
Require with ConventionalViewStrategy.convertModuleIdToViewUrl

### ISSUE THREAD

**Issue by Mordred** [aurelia/loader#7]
Hi, I want to separate templates from js. So I have two directories `/templates/` and `/js/`. Based on documentation I have changed `ConventionalViewStrategy.convertModuleIdToViewUrl` during bootstrap phase:

```js
ConventionalViewStrategy.convertModuleIdToViewUrl = function (moduleId) {
  return moduleId.replace(new RegExp('^js/'), 'templates/') + ".html";
};
```

Problem is that `<require>` now have to have absolute paths, because `./navigation` within `/templates/app.html` is resolved as `/templates/navigation.js`.

Can I somehow change how require loads files?

**Comment by EisenbergEffect** [comment]
I would investigate modifying your conversion function so that it generates urls relative to the module id.

**Comment by Mordred** [comment]
I have tried relative URLs in the conversion function. This line https://github.com/aurelia/loader/blob/master/src/template-registry-entry.js#L48 will always have 

```js
src = "./navigation"
id = "templates/app.html"
```

I've created plunker: http://plnkr.co/edit/LsfRoa?p=preview
